"""Generate the Python types package from bridge_models.py.

Copies all public models and type aliases from bridge_models.py
into types/python/ibkr_bridge_types/models.py as a standalone
Pydantic package (no ib_async dependency).

bridge_models.py is 100% public types (no internal helpers), so
the entire file is copied with only the module docstring replaced.

Usage: python gen_python_types.py
"""

import pathlib
import sys

BRIDGE_MODELS = pathlib.Path("services/bridge/bridge_models.py")
OUTPUT = pathlib.Path("types/python/ibkr_bridge_types/models.py")

HEADER = '''\
"""ibkr-bridge public types — HTTP API and WebSocket event models.

AUTO-GENERATED by gen_python_types.py from bridge_models.py.
Do not edit manually — run `make types` to regenerate.

No dependency on ib_async — pure Pydantic.
"""
'''


def main() -> None:
    if not BRIDGE_MODELS.exists():
        print(f"ERROR: {BRIDGE_MODELS} not found", file=sys.stderr)
        sys.exit(1)

    source = BRIDGE_MODELS.read_text()

    # Replace the original module docstring with our generated header
    body = source
    if body.startswith('"""'):
        closing = body.find('"""', 3)
        if closing != -1:
            body = body[closing + 3:].lstrip("\n")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(HEADER + "\n" + body)

    print(f"Generated {OUTPUT}")


if __name__ == "__main__":
    main()
