"""Generate the Python types package from bridge_models.py.

Two outputs, both fully regenerated on every invocation:

  bridge_models.py  →  types/python/ibkr_bridge_types/models.py
                       (verbatim copy with the docstring replaced)

  bridge_models.py  →  types/python/ibkr_bridge_types/__init__.py
                       (barrel — every top-level public class/alias
                       re-exported via ``from .models import X as X``)

bridge_models.py is 100% public types (no internal helpers), so the
entire file is mirrored. The barrel is computed by AST-walking the
source for top-level ``class``, ``X = ...`` and ``X: T = ...`` defs.

Usage: python gen_python_types.py
"""

import ast
import pathlib
import sys

BRIDGE_MODELS = pathlib.Path("services/bridge/bridge_models.py")
OUT_DIR = pathlib.Path("types/python/ibkr_bridge_types")

MODELS_HEADER = '''\
"""ibkr-bridge public types — HTTP API and WebSocket event models.

AUTO-GENERATED by gen_python_types.py from bridge_models.py.
Do not edit manually — run ``make types`` to regenerate.

No dependency on ib_async — pure Pydantic.
"""
'''

INIT_HEADER = '''\
"""ibkr-bridge-types — Typed Pydantic models for the ibkr-bridge API.

AUTO-GENERATED by gen_python_types.py from bridge_models.py.
Do not edit manually — run ``make types`` to regenerate.
"""
'''


def _strip_docstring(source: str) -> str:
    if source.startswith('"""'):
        end = source.find('"""', 3)
        if end != -1:
            return source[end + 3:].lstrip("\n")
    return source


def _collect_public_names(source: str) -> list[str]:
    """Walk the AST for top-level public name definitions.

    Returns class names plus any module-level assignment / annotated-
    assignment targets. Names starting with ``_`` are filtered out
    (private). Order is alphabetical for deterministic output.
    """
    tree = ast.parse(source)
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            names.add(node.name)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
    return sorted(n for n in names if not n.startswith("_"))


def _render_init(names: list[str]) -> str:
    lines = [INIT_HEADER, ""]
    lines.extend(f"from .models import {n} as {n}" for n in names)
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not BRIDGE_MODELS.exists():
        print(f"ERROR: {BRIDGE_MODELS} not found", file=sys.stderr)
        sys.exit(1)

    source = BRIDGE_MODELS.read_text()

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1. models.py — verbatim copy with our header
    models_path = OUT_DIR / "models.py"
    models_path.write_text(MODELS_HEADER + "\n" + _strip_docstring(source))
    print(f"Generated {models_path}")

    # 2. __init__.py — barrel re-exporting every top-level public name
    init_path = OUT_DIR / "__init__.py"
    names = _collect_public_names(source)
    init_path.write_text(_render_init(names))
    print(f"Generated {init_path} ({len(names)} exports)")


if __name__ == "__main__":
    main()
