/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypesSchema = PlaceOrderPayload | PlaceOrderResponse | HealthResponse | ListTradesResponse;
export type SecType =
  | "BAG"
  | "BOND"
  | "CASH"
  | "CFD"
  | "CMDTY"
  | "CRYPTO"
  | "EVENT"
  | "FOP"
  | "FUND"
  | "FUT"
  | "IND"
  | "NEWS"
  | "OPT"
  | "STK"
  | "WAR";
export type Action = "BUY" | "SELL";
export type OrderType = "LMT" | "MKT";
export type TimeInForce = "DAY" | "DTC" | "FOK" | "GTC" | "GTD" | "IOC" | "OPG";
export type ExecSide = "BOT" | "SLD";

/**
 * Top-level request body for POST /ibkr/order.
 */
export interface PlaceOrderPayload {
  contract: ContractPayload;
  order: OrderPayload;
}
/**
 * Contract fields for identifying the instrument (mirrors ib_async.Contract).
 */
export interface ContractPayload {
  symbol: string;
  secType?: SecType & string;
  exchange?: string;
  currency?: string;
  primaryExchange?: string;
}
/**
 * Order fields for specifying the trade (mirrors ib_async.Order).
 */
export interface OrderPayload {
  action: Action;
  totalQuantity: number;
  orderType: OrderType;
  lmtPrice?: number | null;
  tif?: TimeInForce & string;
  outsideRth?: boolean;
}
export interface PlaceOrderResponse {
  status: string;
  orderId: number;
  action: Action;
  symbol: string;
  totalQuantity: number;
  orderType: OrderType;
  lmtPrice?: number | null;
}
export interface HealthResponse {
  connected: boolean;
  tradingMode: string;
}
export interface ListTradesResponse {
  trades: TradeDetail[];
}
/**
 * A trade with its order info, status, and fills.
 */
export interface TradeDetail {
  orderId: number;
  action: string;
  totalQuantity: number;
  orderType: string;
  lmtPrice?: number | null;
  tif: TimeInForce;
  symbol: string;
  secType: SecType;
  exchange: string;
  currency: string;
  status: string;
  filled: number;
  remaining: number;
  avgFillPrice: number;
  fills: FillDetail[];
}
/**
 * Single execution fill within a trade.
 */
export interface FillDetail {
  execId: string;
  time: string;
  exchange: string;
  side: ExecSide;
  shares: number;
  price: number;
  commission: number;
  commissionCurrency: string;
  realizedPNL: number;
}
