"""ibkr-bridge public types — HTTP API and WebSocket event models.

AUTO-GENERATED by gen_python_types.py from bridge_models.py.
Do not edit manually — run ``make types`` to regenerate.

No dependency on ib_async — pure Pydantic.
"""

from typing import Annotated, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field

# ── Strict union types aligned with ib_async ─────────────────────────

Action = Literal["BUY", "SELL"]

ExecSide = Literal["BOT", "SLD"]

OrderType = Literal["MKT", "LMT"]

SecType = Literal[
    "STK", "OPT", "FUT", "IND", "FOP", "CASH",
    "CFD", "BAG", "WAR", "BOND", "CMDTY", "NEWS",
    "FUND", "CRYPTO", "EVENT",
]

TimeInForce = Literal["DAY", "GTC", "IOC", "GTD", "OPG", "FOK", "DTC"]


# ── POST /ibkr/order ─────────────────────────────────────────────────

class ContractPayload(BaseModel):
    """Contract fields for identifying the instrument (mirrors ib_async.Contract)."""

    model_config = ConfigDict(extra="forbid")

    symbol: str
    secType: SecType = "STK"
    exchange: str = "SMART"
    currency: str = "USD"
    primaryExchange: str = ""


class OrderPayload(BaseModel):
    """Order fields for specifying the trade (mirrors ib_async.Order)."""

    model_config = ConfigDict(extra="forbid")

    action: Action
    totalQuantity: float = Field(gt=0)
    orderType: OrderType
    lmtPrice: float | None = None
    tif: TimeInForce = "DAY"
    outsideRth: bool = False


class PlaceOrderPayload(BaseModel):
    """Top-level request body for POST /ibkr/order."""

    model_config = ConfigDict(extra="forbid")

    contract: ContractPayload
    order: OrderPayload


class PlaceOrderResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: str
    orderId: int  # Permanent order ID (permId from ib_async)
    action: Action
    symbol: str
    totalQuantity: float
    orderType: OrderType
    lmtPrice: float | None = None


# ── GET /health ──────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    connected: bool
    tradingMode: str


# ── GET /ibkr/trades ─────────────────────────────────────────────────

class FillDetail(BaseModel):
    """Single execution fill within a trade."""

    model_config = ConfigDict(extra="forbid")

    execId: str
    time: str
    exchange: str
    side: ExecSide
    shares: float
    price: float
    commission: float
    commissionCurrency: str
    realizedPNL: float


class TradeDetail(BaseModel):
    """A trade with its order info, status, and fills."""

    model_config = ConfigDict(extra="forbid")

    # Order identification
    orderId: int  # Permanent order ID (permId from ib_async)
    action: str  # str not Action — IB may return values beyond BUY/SELL for reads
    totalQuantity: float
    orderType: str  # str not OrderType — IB returns STP, TRAIL, etc. for existing orders
    lmtPrice: float | None = None
    tif: TimeInForce

    # Contract
    symbol: str
    secType: SecType
    exchange: str
    currency: str

    # Status
    status: str
    filled: float
    remaining: float
    avgFillPrice: float

    # Fills
    fills: list[FillDetail]


class ListTradesResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trades: list[TradeDetail]


# ── WebSocket event streaming ────────────────────────────────────────
# Models mirror ib_async 2.1.0 dataclass fields exactly (same names,
# same nesting).  When bumping ib_async, update these models to match.
#
# These models use ``extra="allow"`` (NOT ``extra="forbid"``) because
# they mirror an external upstream (ib_async / IBKR) that can add fields
# without notice.  Unknown fields are preserved in ``model_extra`` so
# downstream consumers can still observe them (and they flow through to
# ``Fill.raw`` in broker_relay).  Required field removal still fails
# validation — only unknown additions are tolerated.

WsEventType = Literal[
    "execDetailsEvent",
    "commissionReportEvent",
    "connected",
    "disconnected",
]

# Provenance of a fill event:
# - ``live`` — emitted by ib_async's push callbacks (execDetailsEvent /
#   commissionReportEvent). Only fires for fills the bridge's IBKR user
#   is authorised to see in real time (typically same-user orders).
# - ``reconciled`` — emitted by the positionEvent → reqExecutions path
#   to surface fills from other users on the same account.
# Status events (``connected`` / ``disconnected``) carry ``source=None``.
WsEventSource = Literal["live", "reconciled"]


class WsComboLeg(BaseModel):
    """Mirrors ib_async.contract.ComboLeg (ib_async 2.1.0)."""

    model_config = ConfigDict(extra="allow")

    conId: int
    ratio: int
    action: str
    exchange: str
    openClose: int
    shortSaleSlot: int
    designatedLocation: str
    exemptCode: int


class WsDeltaNeutralContract(BaseModel):
    """Mirrors ib_async.contract.DeltaNeutralContract (ib_async 2.1.0)."""

    model_config = ConfigDict(extra="allow")

    conId: int
    delta: float
    price: float


class WsContract(BaseModel):
    """Mirrors ib_async.contract.Contract (ib_async 2.1.0)."""

    model_config = ConfigDict(extra="allow")

    secType: str
    conId: int
    symbol: str
    lastTradeDateOrContractMonth: str
    strike: float
    right: str
    multiplier: str
    exchange: str
    primaryExchange: str
    currency: str
    localSymbol: str
    tradingClass: str
    includeExpired: bool
    secIdType: str
    secId: str
    description: str
    issuerId: str
    comboLegsDescrip: str
    comboLegs: list[WsComboLeg] = Field(default_factory=list)
    deltaNeutralContract: WsDeltaNeutralContract | None = None


class WsExecution(BaseModel):
    """Mirrors ib_async.objects.Execution (ib_async 2.1.0)."""

    model_config = ConfigDict(extra="allow")

    execId: str
    time: str
    acctNumber: str
    exchange: str
    side: str
    shares: float
    price: float
    permId: int
    clientId: int
    orderId: int
    liquidation: int
    cumQty: float
    avgPrice: float
    orderRef: str
    evRule: str
    evMultiplier: float
    modelCode: str
    lastLiquidity: int
    pendingPriceRevision: bool


class WsCommissionReport(BaseModel):
    """Mirrors ib_async.objects.CommissionReport (ib_async 2.1.0)."""

    model_config = ConfigDict(extra="allow")

    execId: str
    commission: float
    currency: str
    realizedPNL: float
    yield_: float
    yieldRedemptionDate: int


class WsFill(BaseModel):
    """Mirrors ib_async.objects.Fill NamedTuple (ib_async 2.1.0)."""

    model_config = ConfigDict(extra="allow")

    contract: WsContract
    execution: WsExecution
    commissionReport: WsCommissionReport
    time: str


class WsStatusEnvelope(BaseModel):
    """Connection status event — emitted on (re)connect / disconnect.

    Carries no fill payload because there is no execution to describe.
    """

    model_config = ConfigDict(extra="allow")

    type: Literal["connected", "disconnected"]
    seq: int
    timestamp: str


class WsFillEnvelope(BaseModel):
    """Execution fill event — every fill the bridge surfaces.

    ``fill`` and ``source`` are required: every emitted fill carries a
    full payload and a provenance label (``"live"`` or ``"reconciled"``).
    """

    model_config = ConfigDict(extra="allow")

    type: Literal["execDetailsEvent", "commissionReportEvent"]
    seq: int
    timestamp: str
    fill: WsFill
    source: WsEventSource


# Discriminated union over the ``type`` field. Pydantic uses the
# discriminator to route ``model_validate`` to the correct concrete
# class. Consumers should validate via
# ``TypeAdapter(WsEnvelope).validate_python(data)`` rather than calling
# ``WsEnvelope.model_validate(...)`` — ``WsEnvelope`` is a type alias,
# not a class.
WsEnvelope: TypeAlias = Annotated[
    WsStatusEnvelope | WsFillEnvelope,
    Field(discriminator="type"),
]

